services:
  mongodb:
    image: mongo:8
    container_name: project-orkestra-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ProjectOrkestra
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
